
export const metadata={
    title:'ABM',
    description:'Generated by freelancers',
}

export default function RootPublicPortalLayout({children}){
return(
    <div className="w-[100%]">
        <main>
            {children}
        </main>
    </div>
)
}
