"use client"
import { useSelector } from "react-redux"
import Navbar from "./components/Navbar"
import SidebarMain from "./components/SidebarMain"
import { CircularProgress } from "@mui/joy"
// export const metadata={
//     title:'ABM',
//     description:'Generated by freelancers',
// }

export default function RootPublicPortalLayout({children}){
    const loading=useSelector((state)=>state.loadingShow.loading)
return(
    <div className="w-[100%] flex flex-col">
        {loading?
        <div className="w-[100%] h-[100vh] flex justify-center items-center">
            <CircularProgress/>
        </div>
    :
    (
        <>
        <Navbar/>
        <main className="flex">
        <SidebarMain/>
            {children}
        </main>
        </>
    )    
    }
    </div>
)
}